/**
 * Generates the measurements schema for Rally Study 01.
 */
import fs from 'fs';
import { sharedEvents } from "./measurements.config.mjs"
const boilerplate = {
    "$schema": "http://json-schema.org/draft-04/schema#",
    "mozPipelineMetadata": {
      "bq_dataset_family": "rally_study_01",
      "bq_metadata_format": "pioneer",
      "bq_table": "measurements_v1",
      "expiration_policy": {
        "delete_after_days": 180
      }
    },
    "type": "object",
    "properties": {
      "RS01.userEvent": {
        "oneOf": [
          {
            "type": "object",
            "title": "RS01.attentionEvent",
            "description": "An attention event generated by RS01",
            "properties": {
              ...sharedEvents,
              "maxPixelScrollDepth": {
                "type": "integer",
                "description": "the largest scroll pixel depth reached on the page"
              },
              "maxRelativeScrollDepth": {
                "type": "number",
                "description": "the largest depth reach on the page, as a proportion of the total page height"
              }
            }
          },
          {
            "type": "object",
            "title": "RS01.audioEvent",
            "description": "An attention event generated by RS01",
            "properties": {
              ...sharedEvents,
              "audioStartTime": { "type": "integer" },
              "audioEndTime": { "type": "integer" }
            }
          }
        ]
      }
    }
  }
  
const output = JSON.stringify(boilerplate, null, 2);
fs.writeFileSync('measurements.1.schema.json', output);
console.log('generated new measurements.1.schema.json file')